--NOTE: CREDIT MODEL IS NOT INCLUDED 

SELECT DISTINCT
	 YEAR(DATE_KEY)							 	AS YEAR
	, MONTH(DATE_KEY) 						 	AS MONTH
	, ROUND(SUM(GROSS_AMOUNT),0)			 	AS GROSS_AMOUNT
	, SUM(NET_AMOUNT) 						 	AS NET_AMOUNT
	, IFF(BIG_INDICATOR , DEAL_NAME, 'other') 	AS DEAL
FROM {{ ref('datamart_invoicing') }} SI
LEFT JOIN {{ ref('datamart_dim_deal_active') }}  CDD ON CDD.DEAL_SK = SI.DEAL_SK 
WHERE PAYMENT_SCHEMA != 'Credit model' OR PAYMENT_SCHEMA IS NULL 
GROUP BY 
	 YEAR(DATE_KEY)
	, MONTH(DATE_KEY) 
	, DEAL
	, BIG_INDICATOR
HAVING YEAR IN (2022, 2023, 2024)
ORDER BY 
	 YEAR(DATE_KEY)
	, MONTH(DATE_KEY) 
	, DEAL