WITH CTE AS (
	SELECT DD.DEAL_ID
		, DD.CONTRACT_START_DATE
		, DD.CONTRACT_END_DATE
		-- NOTE: CALCULATE NUMBER OF PAYMENTS PER YEAR
		, CASE DD.PAYMENT_PERIOD
			WHEN 'yearly' 		THEN 12
			WHEN 'quarterly' 	THEN 3
			WHEN 'monthly' 		THEN 1
			WHEN 'biyearly' 	THEN 6
			ELSE 0				END											AS PAYMENT_OCCURRENCE
		, iff( DD.PAYMENT_PERIOD IN ('one time', '') OR DD.PAYMENT_PERIOD IS NULL 
			, 0, DD.ANNUAL_RECURRING_REVENUE/(12/PAYMENT_OCCURRENCE))		AS NET_AMOUNT_PER_INVOICE
		, DD.ONE_OFF_VALUE
	FROM {{ ref('datamart_dim_deal_active') }} dd
	WHERE DD.IS_WON = TRUE
		AND CURRENT_DATE BETWEEN DD.CONTRACT_START_DATE
			AND DD.CONTRACT_END_DATE
)

, CTE2 AS (
	SELECT CTE.DEAL_ID
		, CTE.CONTRACT_START_DATE AS DATE_KEY
		, CTE.CONTRACT_START_DATE
		, CTE.CONTRACT_END_DATE
		, PAYMENT_OCCURRENCE
		, NET_AMOUNT_PER_INVOICE
		, ONE_OFF_VALUE
	FROM CTE
	UNION ALL
	SELECT CTE2.DEAL_ID
		, IFF(DAY(CTE2.DATE_KEY) > 1
			,DATEADD(DAY,1,LAST_DAY(DATEADD(MONTH, PAYMENT_OCCURRENCE, CTE2.DATE_KEY)))
			,DATEADD(MONTH, PAYMENT_OCCURRENCE, CTE2.DATE_KEY ))
		, CTE2.CONTRACT_START_DATE
		, CTE2.CONTRACT_END_DATE
		, PAYMENT_OCCURRENCE
		, NET_AMOUNT_PER_INVOICE
		, ONE_OFF_VALUE
	FROM CTE2
	WHERE DATEADD(MONTH, PAYMENT_OCCURRENCE, CTE2.DATE_KEY ) < CTE2.CONTRACT_END_DATE
		AND CTE2.PAYMENT_OCCURRENCE >= 1
)

, invoices AS (
	SELECT flr.DATE_KEY																AS LAST_INVOICE
		, FLR.PAID_INDICATOR
		, DD.DEAL_ID
		, ROW_NUMBER() OVER (PARTITION BY DD.DEAL_ID ORDER BY FLR.DATE_KEY DESC) 	AS RN
		, COUNT(*) OVER (PARTITION BY DD.DEAL_ID ) 									AS C_INVOICES
	FROM {{ ref('core_fact_revenue') }} flr
		LEFT JOIN {{ ref('datamart_dim_deal_active') }} dd ON flr.DEAL_SK = DD.DEAL_SK 
	WHERE DD.IS_WON = TRUE
		AND CURRENT_DATE BETWEEN DD.CONTRACT_START_DATE
			AND DD.CONTRACT_END_DATE
		AND flr.INVOICE_REVENUE > 0
)

SELECT DISTINCT
	IFNULL(CDD.DEAL_SK, -1)													AS DEAL_SK
	, IFNULL(CDD.COMPANY_SK, -1)											AS COMPANY_SK
	, c.DATE_KEY												 		
	, MAX(IFF(cdc.COUNTRY != 'Germany'
		,c.NET_AMOUNT_PER_INVOICE, c.NET_AMOUNT_PER_INVOICE * 1.19))		AS GROSS_AMOUNT
	, MAX(c.NET_AMOUNT_PER_INVOICE)											AS NET_AMOUNT
	, MAX(IFF(i.LAST_INVOICE < c.DATE_KEY, i.LAST_INVOICE,NULL)) 			AS LAST_INVOICE_BEFORE
	, BOOLAND_AGG(IFF(i.LAST_INVOICE < c.DATE_KEY, i.PAID_INDICATOR,NULL))	AS PAYED_LAST_INVOICE
	, MAX(i.LAST_INVOICE)													AS LAST_INVOICE_ABS
	,  IFF(c.NET_AMOUNT_PER_INVOICE > 750, TRUE, FALSE)   					AS BIG_INDICATOR 
FROM CTE2 c
LEFT JOIN {{ ref('core_dim_deal') }} cdd ON c.DEAL_ID = CDD.DEAL_ID
LEFT JOIN INVOICES i ON i.DEAL_ID = c.DEAL_ID
LEFT JOIN {{ ref('core_dim_company') }} cdc USING(COMPANY_SK)
GROUP BY IFNULL(CDD.DEAL_SK, -1)
	, IFNULL(CDD.COMPANY_SK,-1)
	, DATE_KEY
	, BIG_INDICATOR