version: 2

sources:
  - name: hubspot
    description: Data from Hubspot. See Hubspot's API docs for details.
    database: BI_RAW
    schema: RAW_HUBSPOT
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: companies
      - name: deals
      - name: feedback_submissions
      - name: line_items
      - name: owners
      - name: pipelines
      - name: products
      - name: properties
      - name: quotes
      - name: tickets

  - name: hubspot_engagements
    description: Engagement and contacts Data from Hubspot. See Hubspot's API docs for details.
                 This data is in a separated schema due to the heavy and long data extraction.
    database: BI_RAW
    schema: RAW_HUBSPOT_ENGAGEMENTS
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: engagements
      - name: contacts

  - name: sevdesk
    description: Data from SevDesk. See SevDesk's API docs for details.
    database: BI_RAW
    schema: RAW_SEVDESK
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: invoices
        identifier: "Invoice"
      - name: invoice_items
        identifier: "InvoicePos"
      - name: products
        identifier: "Part"
      - name: customers
        identifier: "Contact"
      - name: receipts
        identifier: "Voucher"
      - name: receipt_items
        identifier: "VoucherPos"
      - name: payments
        identifier: "CheckAccountTransaction"
      - name: communication_way
        identifier: "CommunicationWay"

  - name: flatfiles
    description: Data from flatfiles that are single ingestions
    database: BI_RAW
    schema: RAW_FLATFILES
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: revenue_booked
        identifier: "REVENUE_BOOKED"
        description: Monthly csv file containing DateV data. Located Finance\A_Accounting\A_02_AccountsReceivable\Invoicing\Source\BookedRevenue
      - name: expenses_personnel
        identifier: "EXPENSES_PERSONNELL"
        description: 'Monthly csv file containing personnell data. Generated by python script file'
      - name: portal_suntrol
        identifier: "PORTAL_SUNTROL"
        description: 'Export of all sites in the Suntrol portal'
      - name: portal_solytic_1
        identifier: "PORTAL_SOLYTIC_1"
        description: 'Export of all sites in the Solytic 1.0 portal'
      - name: countries
        identifier: "COUNTRY_CODES"
        description: 'List of countries in multiple languages'
      - name: geographies
        identifier: "COUNTRIES_GEOGRAPHY"
        description: 'Geographies of countries'
      - name: story_points_tech
        identifier: "STORY_POINTS_TECH"
        description: 'Story points overview of the tech/product team'
      - name: sprint_review_tech
        identifier: "SPRINT_REVIEW_TECH"
        description: 'Sprint review/results of the tech/product team'
      - name: ledgers_booked
        identifier: "LEDGERS_BOOKED"
        description: 'List of all ledgers per month with opening, change and end value'
      - name: targets
        identifier: "TARGETS"
        description: 'List of all targets over different departments and granularity'
      - name: azure_costs
        identifier: "AZURE_COSTS"
        description: 'Azure costs automatically ingested by Azure'
      - name: azure_costs_history
        identifier: "AZURE_COSTS_HISTORY"
        description: 'Azure costs history ingested once by Azure'
      - name: jira_issues
        identifier: "JIRA_ISSUES"
        description: 'All Issues from Jira in the PHOEN project'
      - name: s1_renaming
        identifier: "S1_RENAMING"
        description: 'Renaming active S1 companies to fit to hubspot'
      - name: sevdesk_categories
        identifier: "SEVDESK_CATEGORIES"
        description: 'Revenue categories manually managed by the Finance department'

  - name: personio
    database: BI_RAW
    schema: RAW_PERSONIO
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: absences
      - name: attendances
      - name: employees
      - name: projects

  - name: operation
    database: OPERATIONAL_MSSQL
    schema: MODEL
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: company
        identifier: "CUSTOMER"
      - name: device
        identifier: "DEVICE"
      - name: datasource
        identifier: "DATASOURCE"
      - name: datasource_meta
        identifier: "DATASOURCEMETADATA"
      - name: site
        identifier: "SITE"
      - name: address
        identifier: "ADDRESS"
      - name: user
        identifier: "USER"

  - name: operation_metrics
    database: OPERATIONAL_MSSQL
    schema: METRICS
    quoting:
      database: true
      schema: true
      identifier: false
    tables:
      - name: site
        identifier: "SITE"

  - name: operation_tracking
    database: LIBRARY
    schema: TRACKING
    tables:
      - name: api_tracking
        identifier: "API_TRACKING_EVENTS"

  - name: operation_events
    database: LIBRARY
    schema: EVENT
    tables:
      - name: data_source_event
        identifier: "DATA_SOURCE_DAILY_STATISTICS"
