
SELECT
	INVOICE_NUMBER 		    AS INVOICE_NUMBER
	, DATE_KEY				AS DATE_KEY
	, CUSTOMER_ID			AS CUSTOMER_ID
	, TOTAL_CREDIT 			AS TOTAL_CREDIT
	, TOTAL_DEBIT	 		AS TOTAL_DEBIT
	, REVENUE_CATEGORY		AS REVENUE_CATEGORY
FROM {{ ref('staging_flatfiles_booked_revenue') }}