SELECT
	DATE_KEY
    , COMPANY_REPORT_CATEGORY
	, BI_CATEGORY
	, 'C'																				AS CREDIT_DEBIT
	, SUM(AMOUNT_CREDIT 	)															AS BOOKED_AMOUNT
	, SUM(END_BALANCE_CREDIT)  															AS END_BALANCE
FROM {{ ref('staging_flatfiles_ledgers_booked') }}
WHERE COMPANY_REPORT_CATEGORY IS NOT NULL
GROUP BY COMPANY_REPORT_CATEGORY
	, DATE_KEY
	, BI_CATEGORY

UNION ALL

SELECT
	DATE_KEY
    , COMPANY_REPORT_CATEGORY
	, BI_CATEGORY
	, 'D'																				AS CREDIT_DEBIT
	, SUM(AMOUNT_DEBIT	 	)															AS BOOKED_AMOUNT
	, SUM(END_BALANCE_DEBIT	)															AS END_BALANCE
FROM {{ ref('staging_flatfiles_ledgers_booked') }}
WHERE COMPANY_REPORT_CATEGORY IS NOT NULL
GROUP BY COMPANY_REPORT_CATEGORY
	, DATE_KEY
	, BI_CATEGORY